// Autogenerated by thrift-gen. Do not modify.
package stream

import (
	"fmt"

	athrift "github.com/apache/thrift/lib/go/thrift"
	"github.com/uber/tchannel/golang/thrift"
)

// Interfaces for the service and client for the services defined in the IDL.

type TChanTestStream interface {
}

// Implementation of a client and service handler.

type tchanTestStreamClient struct {
	client thrift.TChanClient
}

func NewTChanTestStreamClient(client thrift.TChanClient) TChanTestStream {
	return &tchanTestStreamClient{client: client}
}

type tchanTestStreamServer struct {
	handler TChanTestStream
}

func NewTChanTestStreamServer(handler TChanTestStream) thrift.TChanServer {
	return &tchanTestStreamServer{handler}
}

func (s *tchanTestStreamServer) Service() string {
	return "TestStream"
}

func (s *tchanTestStreamServer) Methods() []string {
	return []string{}
}

func (s *tchanTestStreamServer) Handle(ctx thrift.Context, methodName string, protocol athrift.TProtocol) (bool, athrift.TStruct, error) {
	switch methodName {
	default:
		return false, nil, fmt.Errorf("method %v not found in service %v", methodName, s.Service())
	}
}
