// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package stream

import (
	"bytes"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

type TestStream interface {
	// Parameters:
	//  - Arg1
	BothStream(arg1 *SStringStream) (r *SStringStream, err error)
}

type TestStreamClient struct {
	Transport       thrift.TTransport
	ProtocolFactory thrift.TProtocolFactory
	InputProtocol   thrift.TProtocol
	OutputProtocol  thrift.TProtocol
	SeqId           int32
}

func NewTestStreamClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *TestStreamClient {
	return &TestStreamClient{Transport: t,
		ProtocolFactory: f,
		InputProtocol:   f.GetProtocol(t),
		OutputProtocol:  f.GetProtocol(t),
		SeqId:           0,
	}
}

func NewTestStreamClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *TestStreamClient {
	return &TestStreamClient{Transport: t,
		ProtocolFactory: nil,
		InputProtocol:   iprot,
		OutputProtocol:  oprot,
		SeqId:           0,
	}
}

// Parameters:
//  - Arg1
func (p *TestStreamClient) BothStream(arg1 *SStringStream) (r *SStringStream, err error) {
	if err = p.sendBothStream(arg1); err != nil {
		return
	}
	return p.recvBothStream()
}

func (p *TestStreamClient) sendBothStream(arg1 *SStringStream) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("BothStream", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := BothStreamArgs{
		Arg1: arg1,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *TestStreamClient) recvBothStream() (value *SStringStream, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	_, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error0 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error1 error
		error1, err = error0.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error1
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "BothStream failed: out of sequence response")
		return
	}
	result := BothStreamResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	value = result.GetSuccess()
	return
}

type TestStreamProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      TestStream
}

func (p *TestStreamProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *TestStreamProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *TestStreamProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewTestStreamProcessor(handler TestStream) *TestStreamProcessor {

	self2 := &TestStreamProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self2.processorMap["BothStream"] = &testStreamProcessorBothStream{handler: handler}
	return self2
}

func (p *TestStreamProcessor) Process(iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x3 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x3.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush()
	return false, x3

}

type testStreamProcessorBothStream struct {
	handler TestStream
}

func (p *testStreamProcessorBothStream) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := BothStreamArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("BothStream", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := BothStreamResult{}
	var retval *SStringStream
	var err2 error
	if retval, err2 = p.handler.BothStream(args.Arg1); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing BothStream: "+err2.Error())
		oprot.WriteMessageBegin("BothStream", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("BothStream", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

type BothStreamArgs struct {
	Arg1 *SStringStream `thrift:"arg1,1" json:"arg1"`
}

func NewBothStreamArgs() *BothStreamArgs {
	return &BothStreamArgs{}
}

var BothStreamArgs_Arg1_DEFAULT *SStringStream

func (p *BothStreamArgs) GetArg1() *SStringStream {
	if !p.IsSetArg1() {
		return BothStreamArgs_Arg1_DEFAULT
	}
	return p.Arg1
}
func (p *BothStreamArgs) IsSetArg1() bool {
	return p.Arg1 != nil
}

func (p *BothStreamArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *BothStreamArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Arg1 = &SStringStream{}
	if err := p.Arg1.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.Arg1, err)
	}
	return nil
}

func (p *BothStreamArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("BothStream_args"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *BothStreamArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("arg1", thrift.STRUCT, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:arg1: %s", p, err)
	}
	if err := p.Arg1.Write(oprot); err != nil {
		return fmt.Errorf("%T error writing struct: %s", p.Arg1, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:arg1: %s", p, err)
	}
	return err
}

func (p *BothStreamArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BothStreamArgs(%+v)", *p)
}

type BothStreamResult struct {
	Success *SStringStream `thrift:"success,0" json:"success"`
}

func NewBothStreamResult() *BothStreamResult {
	return &BothStreamResult{}
}

var BothStreamResult_Success_DEFAULT *SStringStream

func (p *BothStreamResult) GetSuccess() *SStringStream {
	if !p.IsSetSuccess() {
		return BothStreamResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BothStreamResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BothStreamResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.ReadField0(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *BothStreamResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = &SStringStream{}
	if err := p.Success.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.Success, err)
	}
	return nil
}

func (p *BothStreamResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("BothStream_result"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField0(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *BothStreamResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			return fmt.Errorf("%T write field begin error 0:success: %s", p, err)
		}
		if err := p.Success.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", p.Success, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 0:success: %s", p, err)
		}
	}
	return err
}

func (p *BothStreamResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BothStreamResult(%+v)", *p)
}
